### ISSUE TITLE
报错libxkbcommon.so.0: version `V_1.0.0' not found

### ISSUE THREAD

**Issue by kero990** [BiliGoldenWater/ChaosDanmuTool#2]
统信uos ，arm64架构
无论可执行文件还是源代码编译，均报错
/lib/aarch64-linux-gnu/libxkbcommon.so.0: version `V_1.0.0' not found
然而系统里存在相关库，估计是强制版本？

> $ ls /lib/aarch64-linux-gnu/libxkbcommon*.*
> /lib/aarch64-linux-gnu/libxkbcommon.a
> /lib/aarch64-linux-gnu/libxkbcommon.so
> /lib/aarch64-linux-gnu/libxkbcommon.so.0
> /lib/aarch64-linux-gnu/libxkbcommon.so.0.0.0
> /lib/aarch64-linux-gnu/libxkbcommon-x11.so.0
> /lib/aarch64-linux-gnu/libxkbcommon-x11.so.0.0.0
>

**Comment by BiliGoldenWater** [comment]
electron的问题
暂时建议编译时更新 electron 或降级 electron 到 17.x 或尝试 19.x
我这 0.10.0 会更新 electron
[electron#issue-33533](https://github.com/electron/electron/issues/33533)
[electron#pull-34155](https://github.com/electron/electron/pull/34155)
